version: '3'

services:
  php_web:
    image: php:7.2.2-apache
    volumes:
      - .:/var/www/html  # Maps the current directory to the Apache document root
    ports:
      - "8100:80"  # Maps port 8100 on the host to port 80 in the container
    stdin_open: true
    tty: true
